### ISSUE TITLE
Keep track of Sovereign light client implementation

### ISSUE THREAD

**Issue by Farhad-Shabani** [informalsystems/sovereign-sdk#14]
## Background
This issue serves as a record of the evolving challenges and milestones in our ongoing pursuit of implementing a Sovereign light client running on Cosmos chains. As we progress, we will update the following list of essential steps:

```[tasklist]
### Tasks
- [ ] Specify the proof specs for the ClientState definition and see if we can coerce our Merkle implementation with existing Jellyfish Merkle implementation
- [ ] Need a query interface for retrieving aggregate SNARK. This should allow querying for a range of aggregate SNAKRS by specifying the start and/or end height
- [ ] Need a way/endpoint to determine the latest height at which an aggregate SNARK is present
- [ ] Prepare an ADR to describe our approach to implementing the Sovereign Light Client
- [ ] Implement a CosmWasm client for Sovereign SDK rollups to run on the Cosmos chains
```
